name: cis-3715-project

channels:
  - apple
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - tensorflow-deps
  - ipykernel

  - pip:
      - tensorflow-macos==2.10
      - tensorflow-metal==0.6
      - tensorflow-addons
      - matplotlib
      - pandas
      - numpy
      - scikit-learn
